<?php
$cities_raw = [
    ["Phoenix", "United States", "usa"],
    ["Philadelphia", "United States", "usa"],
    ["San Antonio", "United States", "usa"],
    ["San Diego", "United States", "usa"],
    ["Dallas", "United States", "usa"],
    ["San Jose", "United States", "usa"],
    ["London", "United Kingdom", "uk"],
    ["Manchester", "United Kingdom", "uk"],
    ["Birmingham", "United Kingdom", "uk"],
    ["Glasgow", "United Kingdom", "uk"],
    ["Toronto", "Canada", "canada"],
    ["Vancouver", "Canada", "canada"],
    ["Montreal", "Canada", "canada"],
    ["Calgary", "Canada", "canada"],
    ["Sydney", "Australia", "australia"],
    ["Melbourne", "Australia", "australia"],
    ["Brisbane", "Australia", "australia"],
    ["Perth", "Australia", "australia"],
    ["Dubai", "UAE", "uae"],
    ["Abu Dhabi", "UAE", "uae"],
    ["Singapore", "Singapore", "singapore"],
    ["Mumbai", "India", "india"],
    ["Delhi", "India", "india"],
    ["Bangalore", "India", "india"],
    ["Hyderabad", "India", "india"],
    ["Chennai", "India", "india"],
    ["Pune", "India", "india"],
    ["Ahmedabad", "India", "india"],
    ["Kolkata", "India", "india"],
    ["Riyadh", "Saudi Arabia", "saudi-arabia"],
    ["Jeddah", "Saudi Arabia", "saudi-arabia"],
    ["Doha", "Qatar", "qatar"],
    ["Kuwait City", "Kuwait", "kuwait"],
    ["Muscat", "Oman", "oman"],
    ["Manama", "Bahrain", "bahrain"],
    ["Johannesburg", "South Africa", "south-africa"],
    ["Cape Town", "South Africa", "south-africa"],
    ["Nairobi", "Kenya", "kenya"],
    ["Lagos", "Nigeria", "nigeria"],
    ["Accra", "Ghana", "ghana"],
    ["Cairo", "Egypt", "egypt"],
    ["Casablanca", "Morocco", "morocco"],
    ["Istanbul", "Turkey", "turkey"],
    ["Ankara", "Turkey", "turkey"],
    ["Berlin", "Germany", "germany"],
    ["Paris", "France", "france"],
    ["Munich", "Germany", "germany"],
    ["Frankfurt", "Germany", "germany"],
    ["Hamburg", "Germany", "germany"],
    ["Madrid", "Spain", "spain"],
    ["Barcelona", "Spain", "spain"],
    ["Milan", "Italy", "italy"],
    ["Rome", "Italy", "italy"],
    ["Amsterdam", "Netherlands", "netherlands"],
    ["Brussels", "Belgium", "belgium"],
    ["Zurich", "Switzerland", "switzerland"],
    ["Vienna", "Austria", "austria"],
    ["Stockholm", "Sweden", "sweden"],
    ["Oslo", "Norway", "norway"],
    ["Copenhagen", "Denmark", "denmark"],
    ["Helsinki", "Finland", "finland"],
    ["Dublin", "Ireland", "ireland"],
    ["Lisbon", "Portugal", "portugal"],
    ["Warsaw", "Poland", "poland"],
    ["Prague", "Czech Republic", "czech-republic"],
    ["Budapest", "Hungary", "hungary"],
    ["Athens", "Greece", "greece"],
    ["Bucharest", "Romania", "romania"],
    ["Sofia", "Bulgaria", "bulgaria"],
    ["Belgrade", "Serbia", "serbia"],
    ["Zagreb", "Croatia", "croatia"],
    ["Ljubljana", "Slovenia", "slovenia"],
    ["Bratislava", "Slovakia", "slovakia"],
    ["Tallinn", "Estonia", "estonia"],
    ["Riga", "Latvia", "latvia"],
    ["Vilnius", "Lithuania", "lithuania"],
    ["Reykjavik", "Iceland", "iceland"],
    ["Luxembourg City", "Luxembourg", "luxembourg"],
    ["Monaco", "Monaco", "monaco"],
    ["San Marino", "San Marino", "san-marino"],
    ["Dammam", "Saudi Arabia", "saudi-arabia"],
    ["Kuala Lumpur", "Malaysia", "malaysia"],
    ["Bangkok", "Thailand", "thailand"],
    ["Manila", "Philippines", "philippines"],
    ["Jakarta", "Indonesia", "indonesia"],
    ["Ho Chi Minh City", "Vietnam", "vietnam"],
    ["Hanoi", "Vietnam", "vietnam"],
    ["Colombo", "Sri Lanka", "sri-lanka"],
    ["Kathmandu", "Nepal", "nepal"],
    ["Dhaka", "Bangladesh", "bangladesh"],
    ["Tokyo", "Japan", "japan"],
    ["Osaka", "Japan", "japan"],
    ["Seoul", "South Korea", "south-korea"],
    ["Auckland", "New Zealand", "new-zealand"],
    ["Wellington", "New Zealand", "new-zealand"],
    ["Christchurch", "New Zealand", "new-zealand"],
    ["Adelaide", "Australia", "australia"],
    ["Canberra", "Australia", "australia"],
    ["San Francisco", "United States", "usa"],
    ["Seattle", "United States", "usa"],
    ["Atlanta", "United States", "usa"],
    ["Boston", "United States", "usa"],
    ["Washington DC", "United States", "usa"],
    ["Denver", "United States", "usa"],
    ["Detroit", "United States", "usa"],
    ["Minneapolis", "United States", "usa"],
    ["Miami", "United States", "usa"],
    ["Las Vegas", "United States", "usa"],
    ["Ottawa", "Canada", "canada"],
    ["Edmonton", "Canada", "canada"],
    ["Quebec City", "Canada", "canada"],
    ["Guadalajara", "Mexico", "mexico"],
    ["Monterrey", "Mexico", "mexico"],
    ["Bogota", "Colombia", "colombia"],
    ["Lima", "Peru", "peru"],
    ["Santiago", "Chile", "chile"],
    ["Buenos Aires", "Argentina", "argentina"],
    ["Rio de Janeiro", "Brazil", "brazil"],
    ["Brasilia", "Brazil", "brazil"],
    ["Cordoba", "Argentina", "argentina"],
    ["Montevideo", "Uruguay", "uruguay"],
    ["Asuncion", "Paraguay", "paraguay"],
    ["La Paz", "Bolivia", "bolivia"],
    ["Quito", "Ecuador", "ecuador"],
    ["Panama City", "Panama", "panama"],
    ["Kingston", "Jamaica", "jamaica"],
    ["Santo Domingo", "Dominican Republic", "dominican-republic"],
    ["Pretoria", "South Africa", "south-africa"],
    ["Durban", "South Africa", "south-africa"],
    ["Addis Ababa", "Ethiopia", "ethiopia"],
    ["Dar es Salaam", "Tanzania", "tanzania"],
    ["Maputo", "Mozambique", "mozambique"],
    ["Tunis", "Tunisia", "tunisia"],
    ["Algiers", "Algeria", "algeria"],
    ["Sharjah", "UAE", "uae"],
    ["Taipei", "Taiwan", "taiwan"],
    ["Hong Kong", "Hong Kong", "hong-kong"],
    ["Orlando", "United States", "usa"],
    ["Austin", "United States", "usa"],
    ["Charlotte", "United States", "usa"],
    ["Columbus", "United States", "usa"],
    ["Indianapolis", "United States", "usa"],
    ["Jacksonville", "United States", "usa"],
    ["Fort Worth", "United States", "usa"],
    ["Nashville", "United States", "usa"],
    ["Portland", "United States", "usa"],
    ["Memphis", "United States", "usa"],
    ["Oklahoma City", "United States", "usa"],
    ["Louisville", "United States", "usa"],
    ["Baltimore", "United States", "usa"],
    ["Milwaukee", "United States", "usa"],
    ["Albuquerque", "United States", "usa"],
    ["Tucson", "United States", "usa"],
    ["Fresno", "United States", "usa"],
    ["Sacramento", "United States", "usa"],
    ["Kansas City", "United States", "usa"],
    ["Mesa", "United States", "usa"]
];

$output = "";
foreach($cities_raw as $c) {
    $city = $c[0];
    $country = $c[1];
    $slug = $c[2];
    
    $cityslug = strtolower(str_replace(' ', '-', $city));
    $cityslug = str_replace('.', '', $cityslug); // remove dots if any
    
    $output .= "            '$cityslug' => [\n";
    $output .= "                'name' => '" . addslashes($city) . "',\n";
    $output .= "                'full' => '" . addslashes($city . ", " . $country) . "',\n";
    $output .= "                'country' => '" . addslashes($country) . "',\n";
    $output .= "                'country_slug' => '$slug',\n";
    $output .= "            ],\n";
}

file_put_contents("C:/Users/ABUBAKAR MALEK/.gemini/antigravity/brain/26b766a0-57b5-4ef6-8fcc-3bdec1559e75/generated_cities.txt", $output);
?>
