<?php

return [
    'aliases' => [
        'us' => 'usa',
        'u-s-a' => 'usa',
        'united-states' => 'usa',
        'united-states-of-america' => 'usa',
        'united-kingdom' => 'uk',
        'great-britain' => 'uk',
        'britain' => 'uk',
        'england' => 'uk',
        'united-arab-emirates' => 'uae',
        'dr-congo' => 'drc-congo',
        'democratic-republic-of-the-congo' => 'drc-congo',
        'congo-kinshasa' => 'drc-congo',
        'republic-of-congo' => 'republic-of-the-congo',
        'congo-brazzaville' => 'republic-of-the-congo',
        'cote-divoire' => 'cote-divoire',
        'cote-d-ivoire' => 'cote-divoire',
        'ivory-coast' => 'cote-divoire',
        'sao-tome-and-principe' => 'sao-tome-and-principe',
        'bosnia-and-herzegovina' => 'bosnia-herzegovina',
        'bosnia-herz' => 'bosnia-herzegovina',
        'saint-kitts-and-nevis' => 'saint-kitts-and-nevis',
        'saint-lucia' => 'saint-lucia',
        'saint-vincent-and-the-grenadines' => 'st-vincent-and-grenadines',
        'saint-vincent-and-grenadines' => 'st-vincent-and-grenadines',
        'saint-vincent-grenadines' => 'st-vincent-and-grenadines',
        'trinidad-tobago' => 'trinidad-and-tobago',
        'antigua-and-barbuda' => 'antigua-and-barbuda',
    ],
    'countries' => [
        'algeria' => ['name' => 'Algeria', 'local_compliance' => 'Law No. 18-07 Compliant'],
        'angola' => ['name' => 'Angola', 'local_compliance' => 'Data Protection Law (Law 22/11) Compliant'],
        'benin' => ['name' => 'Benin', 'local_compliance' => 'Digital Code (Loi No. 2017-20) Compliant'],
        'botswana' => ['name' => 'Botswana', 'local_compliance' => 'Data Protection Act (DPA) Compliant'],
        'burkina-faso' => ['name' => 'Burkina Faso', 'local_compliance' => 'Law No. 010-2004/AN Compliant'],
        'burundi' => ['name' => 'Burundi', 'local_compliance' => 'Data Protection Law (2022) Compliant'],
        'cabo-verde' => ['name' => 'Cabo Verde', 'local_compliance' => 'Law No. 133/V/2001 Compliant'],
        'cameroon' => ['name' => 'Cameroon', 'local_compliance' => 'Framework Law on Cybersecurity & Privacy Compliant'],
        'central-african-republic' => ['name' => 'Central African Republic', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'chad' => ['name' => 'Chad', 'local_compliance' => 'Law No. 007/PR/2015 Compliant'],
        'comoros' => ['name' => 'Comoros', 'local_compliance' => 'Data Protection Law (2014) Compliant'],
        'republic-of-the-congo' => ['name' => 'Republic of the Congo', 'local_compliance' => 'Law No. 29-2019 Compliant'],
        'cote-divoire' => ['name' => 'Côte d’Ivoire', 'local_compliance' => 'Law No. 2013-450 Compliant'],
        'drc-congo' => ['name' => 'DRC (Congo)', 'local_compliance' => 'Law No. 23/010 (Digital Code) Compliant'],
        'djibouti' => ['name' => 'Djibouti', 'local_compliance' => 'Law No. 101/AN/10/6th L Compliant'],
        'egypt' => ['name' => 'Egypt', 'local_compliance' => 'Data Protection Law (Law 151) Compliant'],
        'equatorial-guinea' => ['name' => 'Equatorial Guinea', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'eritrea' => ['name' => 'Eritrea', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'eswatini' => ['name' => 'Eswatini', 'local_compliance' => 'Data Protection Act (2020) Compliant'],
        'ethiopia' => ['name' => 'Ethiopia', 'local_compliance' => 'Data Protection Proclamation (2024) Compliant'],
        'gabon' => ['name' => 'Gabon', 'local_compliance' => 'Law No. 001/2011 Compliant'],
        'the-gambia' => ['name' => 'The Gambia', 'local_compliance' => 'Data Protection Bill Standards Compliant'],
        'ghana' => ['name' => 'Ghana', 'local_compliance' => 'Data Protection Act (Act 843) Compliant'],
        'guinea' => ['name' => 'Guinea', 'local_compliance' => 'Law L/2016/037/AN Compliant'],
        'guinea-bissau' => ['name' => 'Guinea-Bissau', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'kenya' => ['name' => 'Kenya', 'local_compliance' => 'Data Protection Act (2019) Compliant'],
        'lesotho' => ['name' => 'Lesotho', 'local_compliance' => 'Data Protection Act (2011) Compliant'],
        'liberia' => ['name' => 'Liberia', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'libya' => ['name' => 'Libya', 'local_compliance' => 'Personal Data Protection Law Compliant'],
        'madagascar' => ['name' => 'Madagascar', 'local_compliance' => 'Law No. 2014-038 Compliant'],
        'malawi' => ['name' => 'Malawi', 'local_compliance' => 'Data Protection Act (2023) Compliant'],
        'mali' => ['name' => 'Mali', 'local_compliance' => 'Law No. 2013-015 Compliant'],
        'mauritania' => ['name' => 'Mauritania', 'local_compliance' => 'Law No. 2017-020 Compliant'],
        'mauritius' => ['name' => 'Mauritius', 'local_compliance' => 'Data Protection Act (2017) Compliant'],
        'morocco' => ['name' => 'Morocco', 'local_compliance' => 'Law 09-08 Compliant'],
        'mozambique' => ['name' => 'Mozambique', 'local_compliance' => 'Law on Protection of Personal Data Compliant'],
        'namibia' => ['name' => 'Namibia', 'local_compliance' => 'Data Protection Bill Standards Compliant'],
        'niger' => ['name' => 'Niger', 'local_compliance' => 'Law No. 2017-28 Compliant'],
        'nigeria' => ['name' => 'Nigeria', 'local_compliance' => 'NDPA (Nigeria Data Protection Act) Compliant'],
        'rwanda' => ['name' => 'Rwanda', 'local_compliance' => 'Law No. 058/2021 (Data Privacy) Compliant'],
        'sao-tome-and-principe' => ['name' => 'São Tomé and Príncipe', 'local_compliance' => 'Law No. 3/2016 Compliant'],
        'senegal' => ['name' => 'Senegal', 'local_compliance' => 'Law No. 2008-12 Compliant'],
        'seychelles' => ['name' => 'Seychelles', 'local_compliance' => 'Data Protection Act Compliant'],
        'sierra-leone' => ['name' => 'Sierra Leone', 'local_compliance' => 'Data Protection Act (2023) Compliant'],
        'somalia' => ['name' => 'Somalia', 'local_compliance' => 'Data Protection Law Compliant'],
        'south-africa' => ['name' => 'South Africa', 'local_compliance' => 'POPIA (Protection of Personal Information Act) Compliant'],
        'south-sudan' => ['name' => 'South Sudan', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'sudan' => ['name' => 'Sudan', 'local_compliance' => 'Personal Data Protection Standards Compliant'],
        'tanzania' => ['name' => 'Tanzania', 'local_compliance' => 'Personal Data Protection Act (2022) Compliant'],
        'togo' => ['name' => 'Togo', 'local_compliance' => 'Law No. 2019-014 Compliant'],
        'tunisia' => ['name' => 'Tunisia', 'local_compliance' => 'Organic Law No. 2004-63 Compliant'],
        'uganda' => ['name' => 'Uganda', 'local_compliance' => 'Data Protection and Privacy Act (2019) Compliant'],
        'zambia' => ['name' => 'Zambia', 'local_compliance' => 'Data Protection Act (No. 3 of 2021) Compliant'],
        'zimbabwe' => ['name' => 'Zimbabwe', 'local_compliance' => 'Cyber & Data Protection Act (Chapter 12:07) Compliant'],
        'russia' => ['name' => 'Russia', 'local_compliance' => 'Federal Law No. 152-FZ (Personal Data Law) Compliant'],
        'germany' => ['name' => 'Germany', 'local_compliance' => 'GDPR & BDSG Compliant (Bundesdatenschutzgesetz)'],
        'uk' => ['name' => 'United Kingdom', 'local_compliance' => 'UK GDPR & Data (Use and Access) Act 2025 Compliant'],
        'france' => ['name' => 'France', 'local_compliance' => 'GDPR & Loi Informatique et Libertés Compliant'],
        'italy' => ['name' => 'Italy', 'local_compliance' => 'GDPR & Codice della Privacy Compliant'],
        'spain' => ['name' => 'Spain', 'local_compliance' => 'GDPR & LOPDGDD Compliant'],
        'ukraine' => ['name' => 'Ukraine', 'local_compliance' => 'Law on Protection of Personal Data Compliant'],
        'poland' => ['name' => 'Poland', 'local_compliance' => 'GDPR & Personal Data Protection Act Compliant'],
        'romania' => ['name' => 'Romania', 'local_compliance' => 'GDPR & Law No. 190/2018 Compliant'],
        'netherlands' => ['name' => 'Netherlands', 'local_compliance' => 'GDPR & UAVG Compliant'],
        'belgium' => ['name' => 'Belgium', 'local_compliance' => 'GDPR & Data Protection Act 2018 Compliant'],
        'sweden' => ['name' => 'Sweden', 'local_compliance' => 'GDPR & Data Protection Act (2018:218) Compliant'],
        'czech-republic' => ['name' => 'Czech Republic', 'local_compliance' => 'GDPR & Act on Personal Data Processing Compliant'],
        'portugal' => ['name' => 'Portugal', 'local_compliance' => 'GDPR & Law No. 58/2019 Compliant'],
        'greece' => ['name' => 'Greece', 'local_compliance' => 'GDPR & Law 4624/2019 Compliant'],
        'hungary' => ['name' => 'Hungary', 'local_compliance' => 'GDPR & Info Act Compliant'],
        'austria' => ['name' => 'Austria', 'local_compliance' => 'GDPR & DSG (Datenschutzgesetz) Compliant'],
        'switzerland' => ['name' => 'Switzerland', 'local_compliance' => 'Federal Act on Data Protection (nFADP) Compliant'],
        'belarus' => ['name' => 'Belarus', 'local_compliance' => 'Law No. 99-Z (On Personal Data) Compliant'],
        'bulgaria' => ['name' => 'Bulgaria', 'local_compliance' => 'GDPR & Personal Data Protection Act Compliant'],
        'serbia' => ['name' => 'Serbia', 'local_compliance' => 'Law on Personal Data Protection (ZZPL) Compliant'],
        'denmark' => ['name' => 'Denmark', 'local_compliance' => 'GDPR & Data Protection Act Compliant'],
        'norway' => ['name' => 'Norway', 'local_compliance' => 'GDPR & Personal Data Act Compliant'],
        'finland' => ['name' => 'Finland', 'local_compliance' => 'GDPR & Data Protection Act (1050/2018) Compliant'],
        'slovakia' => ['name' => 'Slovakia', 'local_compliance' => 'GDPR & Act No. 18/2018 Compliant'],
        'ireland' => ['name' => 'Ireland', 'local_compliance' => 'GDPR & Data Protection Act 2018 Compliant'],
        'croatia' => ['name' => 'Croatia', 'local_compliance' => 'GDPR & Act on Implementation of GDPR Compliant'],
        'bosnia-herzegovina' => ['name' => 'Bosnia & Herz.', 'local_compliance' => 'Law on Personal Data Protection Compliant'],
        'moldova' => ['name' => 'Moldova', 'local_compliance' => 'Law No. 133 on Personal Data Protection Compliant'],
        'lithuania' => ['name' => 'Lithuania', 'local_compliance' => 'GDPR & Law on Legal Protection of Personal Data Compliant'],
        'albania' => ['name' => 'Albania', 'local_compliance' => 'Law No. 9887 on Protection of Personal Data Compliant'],
        'slovenia' => ['name' => 'Slovenia', 'local_compliance' => 'GDPR & ZVOP-2 Compliant'],
        'latvia' => ['name' => 'Latvia', 'local_compliance' => 'GDPR & Personal Data Processing Law Compliant'],
        'north-macedonia' => ['name' => 'North Macedonia', 'local_compliance' => 'Law on Personal Data Protection Compliant'],
        'estonia' => ['name' => 'Estonia', 'local_compliance' => 'GDPR & Personal Data Protection Act Compliant'],
        'luxembourg' => ['name' => 'Luxembourg', 'local_compliance' => 'GDPR & Act of 1 August 2018 Compliant'],
        'montenegro' => ['name' => 'Montenegro', 'local_compliance' => 'Personal Data Protection Law Compliant'],
        'malta' => ['name' => 'Malta', 'local_compliance' => 'GDPR & Data Protection Act (Cap 586) Compliant'],
        'iceland' => ['name' => 'Iceland', 'local_compliance' => 'GDPR & Act on Data Protection (90/2018) Compliant'],
        'andorra' => ['name' => 'Andorra', 'local_compliance' => 'LQPD (Law 29/2021) Compliant'],
        'liechtenstein' => ['name' => 'Liechtenstein', 'local_compliance' => 'GDPR & Data Protection Act Compliant'],
        'monaco' => ['name' => 'Monaco', 'local_compliance' => 'CCIN (Law No. 1.165) Compliant'],
        'san-marino' => ['name' => 'San Marino', 'local_compliance' => 'Law No. 171 (Data Protection) Compliant'],
        'holy-see' => ['name' => 'Holy See', 'local_compliance' => 'General Decree on Data Protection Compliant'],
        'afghanistan' => ['name' => 'Afghanistan', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'armenia' => ['name' => 'Armenia', 'local_compliance' => 'Law on Protection of Personal Data Compliant'],
        'azerbaijan' => ['name' => 'Azerbaijan', 'local_compliance' => 'Law on Personal Data (No. 998-IIIQ) Compliant'],
        'bahrain' => ['name' => 'Bahrain', 'local_compliance' => 'PDPL (Personal Data Protection Law) Compliant'],
        'bangladesh' => ['name' => 'Bangladesh', 'local_compliance' => 'Data Protection Act (DPA) Standards Compliant'],
        'bhutan' => ['name' => 'Bhutan', 'local_compliance' => 'Information, Communications & Media Act Compliant'],
        'brunei' => ['name' => 'Brunei', 'local_compliance' => 'AITI Data Protection Policy Compliant'],
        'cambodia' => ['name' => 'Cambodia', 'local_compliance' => 'Prakas on Data Protection Compliant'],
        'cyprus' => ['name' => 'Cyprus', 'local_compliance' => 'GDPR & Law 125(I)/2018 Compliant'],
        'georgia' => ['name' => 'Georgia', 'local_compliance' => 'Law on Personal Data Protection Compliant'],
        'india' => ['name' => 'India', 'local_compliance' => 'DPDP Act (Digital Personal Data Protection) Compliant'],
        'indonesia' => ['name' => 'Indonesia', 'local_compliance' => 'PDP Law (Law No. 27 of 2022) Compliant'],
        'iran' => ['name' => 'Iran', 'local_compliance' => 'Personal Data Protection Bill Standards Compliant'],
        'iraq' => ['name' => 'Iraq', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'jordan' => ['name' => 'Jordan', 'local_compliance' => 'Personal Data Protection Law (2023) Compliant'],
        'kazakhstan' => ['name' => 'Kazakhstan', 'local_compliance' => 'Law on Personal Data and its Protection Compliant'],
        'kuwait' => ['name' => 'Kuwait', 'local_compliance' => 'CITRA Data Protection Regulation Compliant'],
        'kyrgyzstan' => ['name' => 'Kyrgyzstan', 'local_compliance' => 'Law on Personal Information (No. 58) Compliant'],
        'laos' => ['name' => 'Laos', 'local_compliance' => 'Law on Protection of Electronic Data Compliant'],
        'lebanon' => ['name' => 'Lebanon', 'local_compliance' => 'Electronic Transactions & Personal Data Law Compliant'],
        'malaysia' => ['name' => 'Malaysia', 'local_compliance' => 'PDPA (Personal Data Protection Act) Compliant'],
        'maldives' => ['name' => 'Maldives', 'local_compliance' => 'Privacy and Personal Data Protection Act Compliant'],
        'mongolia' => ['name' => 'Mongolia', 'local_compliance' => 'Law on Protection of Personal Information Compliant'],
        'myanmar' => ['name' => 'Myanmar', 'local_compliance' => 'Law Protecting Privacy and Security of Citizens Compliant'],
        'nepal' => ['name' => 'Nepal', 'local_compliance' => 'Individual Privacy Act (2018) Compliant'],
        'oman' => ['name' => 'Oman', 'local_compliance' => 'PDP Law (Royal Decree 6/2022) Compliant'],
        'philippines' => ['name' => 'Philippines', 'local_compliance' => 'Data Privacy Act (NPC Circulars) Compliant'],
        'qatar' => ['name' => 'Qatar', 'local_compliance' => 'PDPPL (Law No. 13 of 2016) Compliant'],
        'saudi-arabia' => ['name' => 'Saudi Arabia', 'local_compliance' => 'PDPL (Personal Data Protection Law) Compliant'],
        'singapore' => ['name' => 'Singapore', 'local_compliance' => 'PDPA (Personal Data Protection Act) Compliant'],
        'south-korea' => ['name' => 'South Korea', 'local_compliance' => 'PIPA (Personal Information Protection Act) Compliant'],
        'sri-lanka' => ['name' => 'Sri Lanka', 'local_compliance' => 'Data Protection Act (No. 9 of 2022) Compliant'],
        'syria' => ['name' => 'Syria', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'tajikistan' => ['name' => 'Tajikistan', 'local_compliance' => 'Law on Personal Data (No. 448) Compliant'],
        'thailand' => ['name' => 'Thailand', 'local_compliance' => 'PDPA (Personal Data Protection Act) Compliant'],
        'timor-leste' => ['name' => 'Timor-Leste', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'turkey' => ['name' => 'Turkey', 'local_compliance' => 'KVKK (Law No. 6698) Compliant'],
        'turkmenistan' => ['name' => 'Turkmenistan', 'local_compliance' => 'Law on Information and its Protection Compliant'],
        'uae' => ['name' => 'UAE', 'local_compliance' => 'Federal Decree-Law No. 45 (Data Protection) & SIRA Compliant'],
        'uzbekistan' => ['name' => 'Uzbekistan', 'local_compliance' => 'Law on Personal Data (No. ZRU-547) Compliant'],
        'vietnam' => ['name' => 'Vietnam', 'local_compliance' => 'Decree 13 (Personal Data Protection) Compliant'],
        'yemen' => ['name' => 'Yemen', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'australia' => ['name' => 'Australia', 'local_compliance' => 'Privacy Act 1988 (as amended 2024/2026) & APP Compliant'],
        'new-zealand' => ['name' => 'New Zealand', 'local_compliance' => 'Privacy Act 2020 & IPP 3A (2026) Compliant'],
        'fiji' => ['name' => 'Fiji', 'local_compliance' => 'Constitution of Fiji (Section 24 Privacy Rights) Compliant'],
        'papua-new-guinea' => ['name' => 'Papua New Guinea', 'local_compliance' => 'National Data Governance & Protection Policy Standards'],
        'samoa' => ['name' => 'Samoa', 'local_compliance' => 'Privacy and Personal Data Protection Act Standards'],
        'vanuatu' => ['name' => 'Vanuatu', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'solomon-islands' => ['name' => 'Solomon Islands', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'tonga' => ['name' => 'Tonga', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'kiribati' => ['name' => 'Kiribati', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'marshall-islands' => ['name' => 'Marshall Islands', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'micronesia' => ['name' => 'Micronesia', 'local_compliance' => 'FSM Code (Title 21 Confidentiality) Compliant'],
        'palau' => ['name' => 'Palau', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'nauru' => ['name' => 'Nauru', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'tuvalu' => ['name' => 'Tuvalu', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'canada' => ['name' => 'Canada', 'local_compliance' => 'PIPEDA & Quebec Law 25 Compliant'],
        'usa' => ['name' => 'United States', 'local_compliance' => 'State-Level Comprehensive Privacy Law (CCPA/CPRA) Compliant'],
        'mexico' => ['name' => 'Mexico', 'local_compliance' => 'LFPDPPP (Ley Federal de Protección de Datos Personales) Compliant'],
        'guatemala' => ['name' => 'Guatemala', 'local_compliance' => 'Law for the Protection of Personal Data Standards Compliant'],
        'belize' => ['name' => 'Belize', 'local_compliance' => 'Data Protection Act 2021 Compliant'],
        'el-salvador' => ['name' => 'El Salvador', 'local_compliance' => 'Personal Data Protection Law Standards Compliant'],
        'honduras' => ['name' => 'Honduras', 'local_compliance' => 'Law on Protection of Personal Data Standards Compliant'],
        'nicaragua' => ['name' => 'Nicaragua', 'local_compliance' => 'Law No. 787 (Personal Data Protection) Compliant'],
        'costa-rica' => ['name' => 'Costa Rica', 'local_compliance' => 'Law No. 8968 (Protection of Personal Data) Compliant'],
        'panama' => ['name' => 'Panama', 'local_compliance' => 'Law No. 81 (Personal Data Protection) Compliant'],
        'cuba' => ['name' => 'Cuba', 'local_compliance' => 'Law 149 (Personal Data Protection) Compliant'],
        'haiti' => ['name' => 'Haiti', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'dominican-republic' => ['name' => 'Dominican Republic', 'local_compliance' => 'Law No. 172-13 (Personal Data Protection) Compliant'],
        'bahamas' => ['name' => 'Bahamas', 'local_compliance' => 'Data Protection (Privacy of Personal Information) Act Compliant'],
        'jamaica' => ['name' => 'Jamaica', 'local_compliance' => 'Data Protection Act 2020 Compliant'],
        'barbados' => ['name' => 'Barbados', 'local_compliance' => 'Data Protection Act 2019-29 Compliant'],
        'trinidad-and-tobago' => ['name' => 'Trinidad and Tobago', 'local_compliance' => 'Data Protection Act (Chapter 22:03) Compliant'],
        'antigua-and-barbuda' => ['name' => 'Antigua & Barbuda', 'local_compliance' => 'Data Protection Act 2013 Compliant'],
        'dominica' => ['name' => 'Dominica', 'local_compliance' => 'Data Protection Act 2021 Compliant'],
        'grenada' => ['name' => 'Grenada', 'local_compliance' => 'Data Protection Act 2023 Compliant'],
        'saint-kitts-and-nevis' => ['name' => 'Saint Kitts and Nevis', 'local_compliance' => 'Data Protection Act 2018 Compliant'],
        'saint-lucia' => ['name' => 'Saint Lucia', 'local_compliance' => 'Data Protection Act 2011 Compliant'],
        'st-vincent-and-grenadines' => ['name' => 'St. Vincent & Grenadines', 'local_compliance' => 'Privacy Act 2003 Compliant'],
        'brazil' => ['name' => 'Brazil', 'local_compliance' => 'LGPD (Lei Geral de Proteção de Dados) Compliant'],
        'argentina' => ['name' => 'Argentina', 'local_compliance' => 'Personal Data Protection Act (Law 25.326) Compliant'],
        'chile' => ['name' => 'Chile', 'local_compliance' => 'Law No. 21.719 (LPPD) 2026-Ready Compliant'],
        'colombia' => ['name' => 'Colombia', 'local_compliance' => 'Statutory Law 1581 (Data Protection) Compliant'],
        'peru' => ['name' => 'Peru', 'local_compliance' => 'Law No. 29.733 (Personal Data Protection) Compliant'],
        'uruguay' => ['name' => 'Uruguay', 'local_compliance' => 'Law No. 18.331 (Data Protection) Compliant'],
        'ecuador' => ['name' => 'Ecuador', 'local_compliance' => 'Organic Law on Protection of Personal Data Compliant'],
        'bolivia' => ['name' => 'Bolivia', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'paraguay' => ['name' => 'Paraguay', 'local_compliance' => 'Personal Data Protection Law Standards Compliant'],
        'guyana' => ['name' => 'Guyana', 'local_compliance' => 'Data Protection Act 2023 Compliant'],
        'suriname' => ['name' => 'Suriname', 'local_compliance' => 'International Data Privacy Standards Compliant'],
        'venezuela' => ['name' => 'Venezuela', 'local_compliance' => 'Constitutional Data Privacy Standards Compliant'],
    ],
];
